# Generated by Django 2.2 on 2024-05-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGenerator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.FileField(upload_to='pdf-files'),
        ),
    ]
