# Generated by Django 2.2 on 2024-05-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RGenerator', '0002_auto_20240513_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.FileField(upload_to='pdf-files')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
